apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pd-ecom
  name: pod-reader-ecom
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pd-ecom
  name: pod-writer-ecom
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pd-hcs
  name: pod-reader-hcs
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: pd-hcs
  name: pod-writer-hcs
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-writer
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "update", "patch", "delete"]