apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecom-read-pods
  namespace: pd-ecom
subjects:
  - kind: User
    name: developer-ecom
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-ecom
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ecom-write-pods
  namespace: pd-ecom
subjects:
  - kind: User
    name: developer-ecom
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-writer-ecom
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hcs-read-pods
  namespace: pd-hcs
subjects:
  - kind: User
    name: developer-hcs
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader-hcs
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hcs-write-pods
  namespace: pd-hcs
subjects:
  - kind: User
    name: developer-hcs
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-writer-hcs
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-pods
subjects:
  - kind: User
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: write-pods
subjects:
  - kind: User
    name: devops
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pod-writer
  apiGroup: rbac.authorization.k8s.io